# Autogenerated by devscripts/update-version.py

__version__ = '2023.03.27.155033'

RELEASE_GIT_HEAD = '95a383be1b6fb00c92ee3fb091732c4f6009acb6'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
